baseURL = "https://rfgames.tw/"
languageCode = "en-us"
title = "Stop At Nothing"

disableKinds = [
  "robotsTXT",
  "RSS",
  "sitemap",
  "taxonomy",
  "term"
]

defaultContentLanguage = "en-us"
disableAliases = true
enableRobotsTXT = false
hasCJKLanguage = true
relativeURLs = true

disqusShortname = "rfgames"
googleAnalytics = "UA-109064425-4"

[params]
  applicationFormURL = "https://api.rfgames.tw/v1/apply"
  contactFormURL = "https://api.rfgames.tw/v1/contact"
  description = "A NA SEA fight-focused WvW guild"
  gitRepository = "https://github.com/progamesigner/rfgames-web"
  gw2APILanguage = 'en'
  gw2APISchemaVersion = '2021-01-01T00:00:00Z'
  gw2WikiLanguage = 'en'

[security]
  [security.funcs]
    getenv = ['^GW2_', '^HUGO_']
