baseURL = "https://rfgames.tw/"
languageCode = "en-us"
title = "Stop At Nothing [Rush]"

disableKinds = [
  "404",
  "robotsTXT",
  "RSS",
  "sitemap",
  "taxonomy",
  "taxonomyTerm"
]

defaultContentLanguage = "en-us"
disableAliases = true
enableRobotsTXT = false
hasCJKLanguage = true
relativeURLs = true
