baseURL = "https://rfgames.tw/"
languageCode = "en-us"
title = "Stop At Nothing [Rush]"

disableKinds = [
  "404",
  "robotsTXT",
  "RSS",
  "sitemap",
  "taxonomy",
  "taxonomyTerm"
]

defaultContentLanguage = "en-us"
disableAliases = true
enableRobotsTXT = false
hasCJKLanguage = true
relativeURLs = true

[params]
  applicationFormURL = "https://apis.rfgames.tw/v1/apply"
  contactFormURL = "https://apis.rfgames.tw/v1/contact"
  footer = "<p>Made with <span class=\"has-text-danger\">&hearts;</span> by Stop At Nothing [Rush].</p>"
