baseURL = "https://rfgames.tw/"
languageCode = "en-us"
title = "Stop At Nothing"

disableKinds = [
  "robotsTXT",
  "RSS",
  "sitemap",
  "taxonomy",
  "taxonomyTerm"
]

defaultContentLanguage = "en-us"
disableAliases = true
enableRobotsTXT = false
hasCJKLanguage = true
relativeURLs = true

disqusShortname = "rfgames"
googleAnalytics = "UA-109064425-4"

[params]
  applicationFormURL = "https://api.rfgames.tw/v1/apply"
  contactFormURL = "https://api.rfgames.tw/v1/contact"
  description = "A NA SEA fight-focused WvW guild"
  gitRepository = "https://github.com/progamesigner/rfgames-web"
